C **************************************************************** 
C                                                                  
C Sparse Data Header File                                          
C                                                                  
C Generated by KPP - symbolic chemistry Kinetics PreProcessor      
C     KPP is developed at CGRER labs University of Iowa by         
C     Valeriu Damian & Adrian Sandu                                
C                                                                  
C File                 : saprcnov_stem_s.h                         
C Time                 : Fri Nov 22 13:53:54 2002                  
C Working directory    : /home/asandu/kpp-1.2/examples             
C Equation file        : saprcnov_stem.k                           
C Output root filename : saprcnov_stem                             
C                                                                  
C **************************************************************** 



      INCLUDE 'saprcnov_stem.h'
C                                                                  
C Sparse data                                                      
C                                                                  
C IROW_V - row indexes for the Jacobian of variables               
      INTEGER IROW_V(NONZERO_V)
      COMMON /SDATA/ IROW_V
C ICOL_V - column indexes for the Jacobian of variables            
      INTEGER ICOL_V(NONZERO_V)
      COMMON /SDATA/ ICOL_V
C CROW_V - compressed row indexes for the Jacobian of variables    
      INTEGER CROW_V(CNVAR)
      COMMON /SDATA/ CROW_V
C DIAG_V - diagonal indexes for the Jacobian of variables          
      INTEGER DIAG_V(CNVAR)
      COMMON /SDATA/ DIAG_V
C LU_IROW_V - row indexes for the LU Jacobian of variables         
      INTEGER LU_IROW_V(LU_NONZERO_V)
      COMMON /SDATA/ LU_IROW_V
C LU_ICOL_V - column indexes for the LU Jacobian of variables      
      INTEGER LU_ICOL_V(974)
      COMMON /SDATA/ LU_ICOL_V
C LU_CROW_V - compressed row indexes for the LU Jacobian of variables
      INTEGER LU_CROW_V(89)
      COMMON /SDATA/ LU_CROW_V
C LU_DIAG_V - diagonal indexes for the LU Jacobian of variables    
      INTEGER LU_DIAG_V(89)
      COMMON /SDATA/ LU_DIAG_V
C IROW_R - row indexes for the Jacobian of radicals                
      INTEGER IROW_R(NONZERO_R+1)
      COMMON /SDATA/ IROW_R
C ICOL_R - column indexes for the Jacobian of radicals             
      INTEGER ICOL_R(NONZERO_R+1)
      COMMON /SDATA/ ICOL_R
C CROW_R - compressed row indexes for the Jacobian of radicals     
      INTEGER CROW_R(CNRAD)
      COMMON /SDATA/ CROW_R
C DIAG_R - diagonal indexes for the Jacobian of radicals           
      INTEGER DIAG_R(CNRAD)
      COMMON /SDATA/ DIAG_R

C                                                                  
C Sparse Hessian data                                              
C                                                                  
C IHESS_I - index i for Hessian d^2 f_i/dv_j.dv_k                  
      INTEGER IHESS_I(893)
      COMMON /HESSDATA/ IHESS_I
C IHESS_J - index j for Hessian d^2 f_i/dv_j.dv_k                  
      INTEGER IHESS_J(893)
      COMMON /HESSDATA/ IHESS_J
C IHESS_K - index k for Hessian d^2 f_i/dv_j.dv_k                  
      INTEGER IHESS_K(893)
      COMMON /HESSDATA/ IHESS_K

