C **************************************************************** 
C                                                                  
C Global Header File                                               
C                                                                  
C Generated by KPP - symbolic chemistry Kinetics PreProcessor      
C     KPP is developed at CGRER labs University of Iowa by         
C     Valeriu Damian & Adrian Sandu                                
C                                                                  
C File                 : saprcnov_stem.h                           
C Time                 : Fri Nov 22 13:53:54 2002                  
C Working directory    : /home/asandu/kpp-1.2/examples             
C Equation file        : saprcnov_stem.k                           
C Output root filename : saprcnov_stem                             
C                                                                  
C **************************************************************** 



      IMPLICIT REAL*8 ( A-H, O-Z )

C NSPEC - The number of species involved                           
      INTEGER NSPEC
      PARAMETER ( NSPEC = 93 )
C NVAR - The number of Variable species                            
      INTEGER NVAR
      PARAMETER ( NVAR = 88 )
C NVARACT - The number of Active species                           
      INTEGER NVARACT
      PARAMETER ( NVARACT = 81 )
C NRAD - The number of Radical species                             
      INTEGER NRAD
      PARAMETER ( NRAD = 1 )
C NFIX - The number of Fixed species                               
      INTEGER NFIX
      PARAMETER ( NFIX = 5 )
C NREACT - The number of reactions                                 
      INTEGER NREACT
      PARAMETER ( NREACT = 235 )
C NVARST - Starting of variables in conc. vect.                    
      INTEGER NVARST
      PARAMETER ( NVARST = 0 )
C NRADST - Starting of radicals in conc. vect.                     
      INTEGER NRADST
      PARAMETER ( NRADST = 88 )
C NFIXST - Starting of fixed in conc. vect.                        
      INTEGER NFIXST
      PARAMETER ( NFIXST = 88 )
C NONZERO_V - Number of nonzero variable elements                  
      INTEGER NONZERO_V
      PARAMETER ( NONZERO_V = 893 )
C LU_NONZERO_V - Number of nonzero variable LU elements            
      INTEGER LU_NONZERO_V
      PARAMETER ( LU_NONZERO_V = 974 )
C NONZERO_R - Number of nonzero radical elements                   
      INTEGER NONZERO_R
      PARAMETER ( NONZERO_R = 0 )
C CNVAR - (NVAR+1) The number of elements in compressed row format 
      INTEGER CNVAR
      PARAMETER ( CNVAR = NVAR + 1 )
C CNRAD - (NRAD+1) The number of elements in compressed row format 
      INTEGER CNRAD
      PARAMETER ( CNRAD = NRAD + 1 )
C NHESS - Length of Sparse Hessian                                 
      INTEGER NHESS
      PARAMETER ( NHESS = 893 )
C NLOOKAT - number of species to look at                           
      INTEGER NLOOKAT
      PARAMETER ( NLOOKAT = 93 )
C NMONITOR - number of species to monitor                          
      INTEGER NMONITOR
      PARAMETER ( NMONITOR = 1 )
C NMASS - number of atoms to check mass balance                    
      INTEGER NMASS
      PARAMETER ( NMASS = 0 )
C NX - X grid dimension                                            
      INTEGER NX
      PARAMETER ( NX = 0 )
C NY - Y grid dimension                                            
      INTEGER NY
      PARAMETER ( NY = 0 )
C NZ - Z grid dimension                                            
      INTEGER NZ
      PARAMETER ( NZ = 0 )
C MAX_XYZ - maximum grid dimension                                 
      INTEGER MAX_XYZ
      PARAMETER ( MAX_XYZ = 0 )
C NS - number of species to transport                              
      INTEGER NS
      PARAMETER ( NS = 0 )
C PI - Value of pi                                                 
      REAL*8 PI
      PARAMETER ( PI = 3.14159265358979 )


C Indexes declaration for variable species                         

      INTEGER I_H2SO4
      PARAMETER ( I_H2SO4 = 1 )
      INTEGER I_BC
      PARAMETER ( I_BC = 2 )
      INTEGER I_OC
      PARAMETER ( I_OC = 3 )
      INTEGER I_SSF
      PARAMETER ( I_SSF = 4 )
      INTEGER I_SSC
      PARAMETER ( I_SSC = 5 )
      INTEGER I_PM10
      PARAMETER ( I_PM10 = 6 )
      INTEGER I_PM25
      PARAMETER ( I_PM25 = 7 )
      INTEGER I_DMS
      PARAMETER ( I_DMS = 8 )
      INTEGER I_DST1
      PARAMETER ( I_DST1 = 9 )
      INTEGER I_DST2
      PARAMETER ( I_DST2 = 10 )
      INTEGER I_DST3
      PARAMETER ( I_DST3 = 11 )
      INTEGER I_CO2
      PARAMETER ( I_CO2 = 12 )
      INTEGER I_HCOOH
      PARAMETER ( I_HCOOH = 13 )
      INTEGER I_CCO_OH
      PARAMETER ( I_CCO_OH = 14 )
      INTEGER I_RCO_OH
      PARAMETER ( I_RCO_OH = 15 )
      INTEGER I_CCO_OOH
      PARAMETER ( I_CCO_OOH = 16 )
      INTEGER I_RCO_OOH
      PARAMETER ( I_RCO_OOH = 17 )
      INTEGER I_XN
      PARAMETER ( I_XN = 18 )
      INTEGER I_XC
      PARAMETER ( I_XC = 19 )
      INTEGER I_SO2
      PARAMETER ( I_SO2 = 20 )
      INTEGER I_O1D
      PARAMETER ( I_O1D = 21 )
      INTEGER I_C2H6
      PARAMETER ( I_C2H6 = 22 )
      INTEGER I_BACL
      PARAMETER ( I_BACL = 23 )
      INTEGER I_PAN
      PARAMETER ( I_PAN = 24 )
      INTEGER I_PAN2
      PARAMETER ( I_PAN2 = 25 )
      INTEGER I_PBZN
      PARAMETER ( I_PBZN = 26 )
      INTEGER I_MA_PAN
      PARAMETER ( I_MA_PAN = 27 )
      INTEGER I_H2O2
      PARAMETER ( I_H2O2 = 28 )
      INTEGER I_C3H8
      PARAMETER ( I_C3H8 = 29 )
      INTEGER I_ETOH
      PARAMETER ( I_ETOH = 30 )
      INTEGER I_N2O5
      PARAMETER ( I_N2O5 = 31 )
      INTEGER I_HONO
      PARAMETER ( I_HONO = 32 )
      INTEGER I_ALK3
      PARAMETER ( I_ALK3 = 33 )
      INTEGER I_TBU_O
      PARAMETER ( I_TBU_O = 34 )
      INTEGER I_ALK5
      PARAMETER ( I_ALK5 = 35 )
      INTEGER I_ARO2
      PARAMETER ( I_ARO2 = 36 )
      INTEGER I_HNO4
      PARAMETER ( I_HNO4 = 37 )
      INTEGER I_COOH
      PARAMETER ( I_COOH = 38 )
      INTEGER I_HOCOO
      PARAMETER ( I_HOCOO = 39 )
      INTEGER I_BZNO2_O
      PARAMETER ( I_BZNO2_O = 40 )
      INTEGER I_MEOH
      PARAMETER ( I_MEOH = 41 )
      INTEGER I_ALK4
      PARAMETER ( I_ALK4 = 42 )
      INTEGER I_ARO1
      PARAMETER ( I_ARO1 = 43 )
      INTEGER I_DCB3
      PARAMETER ( I_DCB3 = 44 )
      INTEGER I_DCB2
      PARAMETER ( I_DCB2 = 45 )
      INTEGER I_CRES
      PARAMETER ( I_CRES = 46 )
      INTEGER I_C2H2
      PARAMETER ( I_C2H2 = 47 )
      INTEGER I_DCB1
      PARAMETER ( I_DCB1 = 48 )
      INTEGER I_BALD
      PARAMETER ( I_BALD = 49 )
      INTEGER I_ROOH
      PARAMETER ( I_ROOH = 50 )
      INTEGER I_NPHE
      PARAMETER ( I_NPHE = 51 )
      INTEGER I_PHEN
      PARAMETER ( I_PHEN = 52 )
      INTEGER I_CO
      PARAMETER ( I_CO = 53 )
      INTEGER I_MGLY
      PARAMETER ( I_MGLY = 54 )
      INTEGER I_ACET
      PARAMETER ( I_ACET = 55 )
      INTEGER I_HNO3
      PARAMETER ( I_HNO3 = 56 )
      INTEGER I_ETHENE
      PARAMETER ( I_ETHENE = 57 )
      INTEGER I_C3H6
      PARAMETER ( I_C3H6 = 58 )
      INTEGER I_GLY
      PARAMETER ( I_GLY = 59 )
      INTEGER I_BZ_O
      PARAMETER ( I_BZ_O = 60 )
      INTEGER I_ISOPRENE
      PARAMETER ( I_ISOPRENE = 61 )
      INTEGER I_R2O2
      PARAMETER ( I_R2O2 = 62 )
      INTEGER I_TERP
      PARAMETER ( I_TERP = 63 )
      INTEGER I_METHACRO
      PARAMETER ( I_METHACRO = 64 )
      INTEGER I_OLE1
      PARAMETER ( I_OLE1 = 65 )
      INTEGER I_ISOPROD
      PARAMETER ( I_ISOPROD = 66 )
      INTEGER I_OLE2
      PARAMETER ( I_OLE2 = 67 )
      INTEGER I_MVK
      PARAMETER ( I_MVK = 68 )
      INTEGER I_CCHO
      PARAMETER ( I_CCHO = 69 )
      INTEGER I_HCHO
      PARAMETER ( I_HCHO = 70 )
      INTEGER I_RNO3
      PARAMETER ( I_RNO3 = 71 )
      INTEGER I_O3P
      PARAMETER ( I_O3P = 72 )
      INTEGER I_RCHO
      PARAMETER ( I_RCHO = 73 )
      INTEGER I_MEK
      PARAMETER ( I_MEK = 74 )
      INTEGER I_PROD2
      PARAMETER ( I_PROD2 = 75 )
      INTEGER I_O3
      PARAMETER ( I_O3 = 76 )
      INTEGER I_BZCO_O2
      PARAMETER ( I_BZCO_O2 = 77 )
      INTEGER I_HO2
      PARAMETER ( I_HO2 = 78 )
      INTEGER I_OH
      PARAMETER ( I_OH = 79 )
      INTEGER I_MA_RCO3
      PARAMETER ( I_MA_RCO3 = 80 )
      INTEGER I_NO
      PARAMETER ( I_NO = 81 )
      INTEGER I_NO3
      PARAMETER ( I_NO3 = 82 )
      INTEGER I_C_O2
      PARAMETER ( I_C_O2 = 83 )
      INTEGER I_CCO_O2
      PARAMETER ( I_CCO_O2 = 84 )
      INTEGER I_NO2
      PARAMETER ( I_NO2 = 85 )
      INTEGER I_RO2_N
      PARAMETER ( I_RO2_N = 86 )
      INTEGER I_RO2_R
      PARAMETER ( I_RO2_R = 87 )
      INTEGER I_RCO_O2
      PARAMETER ( I_RCO_O2 = 88 )

C Indexes declaration for radical species                          


C Indexes declaration for fixed species                            

      INTEGER I_AIR
      PARAMETER ( I_AIR = 1 )
      INTEGER I_O2
      PARAMETER ( I_O2 = 2 )
      INTEGER I_H2O
      PARAMETER ( I_H2O = 3 )
      INTEGER I_H2
      PARAMETER ( I_H2 = 4 )
      INTEGER I_CH4
      PARAMETER ( I_CH4 = 5 )

C User defined variables                                           

      INTEGER ISNOTAUTONOM
      COMMON /INTGDATA/ ISNOTAUTONOM
      REAL*8 STEPSTART
      COMMON /GDATA/ STEPSTART

C End user defined variables                                       

