C **************************************************************** 
C                                                                  
C Auxiliary Routines File                                          
C                                                                  
C Generated by KPP - symbolic chemistry Kinetics PreProcessor      
C     KPP is developed at CGRER labs University of Iowa by         
C     Valeriu Damian & Adrian Sandu                                
C                                                                  
C File                 : saprcnov_stem_util.f                      
C Time                 : Fri Nov 22 13:53:54 2002                  
C Working directory    : /home/asandu/kpp-1.2/examples             
C Equation file        : saprcnov_stem.k                           
C Output root filename : saprcnov_stem                             
C                                                                  
C **************************************************************** 



C **************************************************************** 
C                                                                  
C UTIL - Utility functions                                         
C   Arguments :                                                    
C                                                                  
C **************************************************************** 

C ****************************************************************
C                            
C InitSaveData - Opens the data file for writing
C   Parameters :                                                  
C
C ****************************************************************

      SUBROUTINE InitSaveData ()

      INCLUDE 'saprcnov_stem.h'

      open(10, file='saprcnov_stem.dat')

      RETURN
      END

C End of InitSaveData function
C ****************************************************************

C ****************************************************************
C                            
C SaveData - Write LOOKAT species in the data file 
C   Parameters :                                                  
C
C ****************************************************************

      SUBROUTINE SaveData ()

      INCLUDE 'saprcnov_stem.h'

      INTEGER i

      WRITE(10,999) (TIME-TSTART)/3600.D0,
     *              (C(LOOKAT(i))/CFACTOR, i=1,NLOOKAT)
999   FORMAT(E24.16,100(1X,E24.16))

      RETURN
      END

C End of SaveData function
C ****************************************************************

C ****************************************************************
C                            
C CloseSaveData - Close the data file 
C   Parameters :                                                  
C
C ****************************************************************

      SUBROUTINE CloseSaveData ()

      INCLUDE 'saprcnov_stem.h'

      CLOSE(10)

      RETURN
      END

C End of CloseSaveData function
C ****************************************************************

C ****************************************************************
C                            
C GenerateMatlab - Generates MATLAB file to load the data file 
C   Parameters : 
C                It will have a character string to prefix each 
C                species name with.                                                 
C
C ****************************************************************

      SUBROUTINE GenerateMatlab ( PREFIX )

      INCLUDE 'saprcnov_stem.h'
      
      CHARACTER*8 PREFIX 
      INTEGER i

      open(20, file='saprcnov_stem.m')
      write(20,*) 'load saprcnov_stem.dat;'
      write(20,990) PREFIX
990   FORMAT(A1,'c = saprcnov_stem;')
      write(20,*) 'clear saprcnov_stem;'
      write(20,991) PREFIX, PREFIX
991   FORMAT(A1,'t=',A1,'c(:,1);')
      write(20,992) PREFIX
992   FORMAT(A1,'c(:,1)=[];')

      do i=1,NLOOKAT
        write(20,993) PREFIX, SLOOKAT(i), PREFIX, i
993     FORMAT(A1,A6,' = ',A1,'c(:,',I2,');')
      end do
      
      CLOSE(20)

      RETURN
      END

C End of GenerateMatlab function
C ****************************************************************

C End of UTIL function                                             
C **************************************************************** 


C **************************************************************** 
C                                                                  
C UseConc - function to copy concentrations from USER to KPP       
C   Arguments :                                                    
C      U_VAR     - Concentration of variable species in USER's order
C      U_RAD     - Concentration of radical species in USER's order
C                                                                  
C **************************************************************** 

      SUBROUTINE UseConc ( U_VAR, U_RAD )

      INCLUDE 'saprcnov_stem.h'

C U_VAR - Concentration of variable species in USER's order        
      REAL*8 U_VAR(NVAR)
C U_RAD - Concentration of radical species in USER's order         
      REAL*8 U_RAD(NVAR)

      C(76) = U_VAR(1)
      C(28) = U_VAR(2)
      C(81) = U_VAR(3)
      C(85) = U_VAR(4)
      C(82) = U_VAR(5)
      C(31) = U_VAR(6)
      C(32) = U_VAR(7)
      C(56) = U_VAR(8)
      C(37) = U_VAR(9)
      C(20) = U_VAR(10)
      C(1) = U_VAR(11)
      C(53) = U_VAR(12)
      C(70) = U_VAR(13)
      C(69) = U_VAR(14)
      C(73) = U_VAR(15)
      C(55) = U_VAR(16)
      C(74) = U_VAR(17)
      C(13) = U_VAR(18)
      C(41) = U_VAR(19)
      C(30) = U_VAR(20)
      C(14) = U_VAR(21)
      C(15) = U_VAR(22)
      C(59) = U_VAR(23)
      C(54) = U_VAR(24)
      C(23) = U_VAR(25)
      C(46) = U_VAR(26)
      C(49) = U_VAR(27)
      C(66) = U_VAR(28)
      C(64) = U_VAR(29)
      C(68) = U_VAR(30)
      C(75) = U_VAR(31)
      C(48) = U_VAR(32)
      C(45) = U_VAR(33)
      C(44) = U_VAR(34)
      C(57) = U_VAR(35)
      C(61) = U_VAR(36)
      C(22) = U_VAR(37)
      C(29) = U_VAR(38)
      C(47) = U_VAR(39)
      C(58) = U_VAR(40)
      C(33) = U_VAR(41)
      C(42) = U_VAR(42)
      C(35) = U_VAR(43)
      C(43) = U_VAR(44)
      C(36) = U_VAR(45)
      C(65) = U_VAR(46)
      C(67) = U_VAR(47)
      C(63) = U_VAR(48)
      C(71) = U_VAR(49)
      C(51) = U_VAR(50)
      C(52) = U_VAR(51)
      C(24) = U_VAR(52)
      C(25) = U_VAR(53)
      C(26) = U_VAR(54)
      C(27) = U_VAR(55)
      C(2) = U_VAR(56)
      C(3) = U_VAR(57)
      C(4) = U_VAR(58)
      C(5) = U_VAR(59)
      C(6) = U_VAR(60)
      C(7) = U_VAR(61)
      C(8) = U_VAR(62)
      C(9) = U_VAR(63)
      C(10) = U_VAR(64)
      C(11) = U_VAR(65)
      C(12) = U_VAR(66)
      C(16) = U_VAR(67)
      C(88) = U_VAR(68)
      C(17) = U_VAR(69)
      C(18) = U_VAR(70)
      C(19) = U_VAR(71)
      C(72) = U_VAR(72)
      C(21) = U_VAR(73)
      C(79) = U_VAR(74)
      C(78) = U_VAR(75)
      C(83) = U_VAR(76)
      C(38) = U_VAR(77)
      C(50) = U_VAR(78)
      C(87) = U_VAR(79)
      C(62) = U_VAR(80)
      C(86) = U_VAR(81)
      C(39) = U_VAR(82)
      C(84) = U_VAR(83)
      C(77) = U_VAR(84)
      C(40) = U_VAR(85)
      C(60) = U_VAR(86)
      C(80) = U_VAR(87)
      C(34) = U_VAR(88)
      C(89) = C_DEFAULT(89)
      C(90) = C_DEFAULT(90)
      C(91) = C_DEFAULT(91)
      RETURN
      END

C End of UseConc function                                          
C **************************************************************** 


C **************************************************************** 
C                                                                  
C RestConc - function to restore concentrations from KPP to USER   
C   Arguments :                                                    
C      U_VAR     - Concentration of variable species in USER's order
C      U_RAD     - Concentration of radical species in USER's order
C                                                                  
C **************************************************************** 

      SUBROUTINE RestConc ( U_VAR, U_RAD )

      INCLUDE 'saprcnov_stem.h'

C U_VAR - Concentration of variable species in USER's order        
      REAL*8 U_VAR(NVAR)
C U_RAD - Concentration of radical species in USER's order         
      REAL*8 U_RAD(NVAR)

      U_VAR(1) = C(76)
      U_VAR(2) = C(28)
      U_VAR(3) = C(81)
      U_VAR(4) = C(85)
      U_VAR(5) = C(82)
      U_VAR(6) = C(31)
      U_VAR(7) = C(32)
      U_VAR(8) = C(56)
      U_VAR(9) = C(37)
      U_VAR(10) = C(20)
      U_VAR(11) = C(1)
      U_VAR(12) = C(53)
      U_VAR(13) = C(70)
      U_VAR(14) = C(69)
      U_VAR(15) = C(73)
      U_VAR(16) = C(55)
      U_VAR(17) = C(74)
      U_VAR(18) = C(13)
      U_VAR(19) = C(41)
      U_VAR(20) = C(30)
      U_VAR(21) = C(14)
      U_VAR(22) = C(15)
      U_VAR(23) = C(59)
      U_VAR(24) = C(54)
      U_VAR(25) = C(23)
      U_VAR(26) = C(46)
      U_VAR(27) = C(49)
      U_VAR(28) = C(66)
      U_VAR(29) = C(64)
      U_VAR(30) = C(68)
      U_VAR(31) = C(75)
      U_VAR(32) = C(48)
      U_VAR(33) = C(45)
      U_VAR(34) = C(44)
      U_VAR(35) = C(57)
      U_VAR(36) = C(61)
      U_VAR(37) = C(22)
      U_VAR(38) = C(29)
      U_VAR(39) = C(47)
      U_VAR(40) = C(58)
      U_VAR(41) = C(33)
      U_VAR(42) = C(42)
      U_VAR(43) = C(35)
      U_VAR(44) = C(43)
      U_VAR(45) = C(36)
      U_VAR(46) = C(65)
      U_VAR(47) = C(67)
      U_VAR(48) = C(63)
      U_VAR(49) = C(71)
      U_VAR(50) = C(51)
      U_VAR(51) = C(52)
      U_VAR(52) = C(24)
      U_VAR(53) = C(25)
      U_VAR(54) = C(26)
      U_VAR(55) = C(27)
      U_VAR(56) = C(2)
      U_VAR(57) = C(3)
      U_VAR(58) = C(4)
      U_VAR(59) = C(5)
      U_VAR(60) = C(6)
      U_VAR(61) = C(7)
      U_VAR(62) = C(8)
      U_VAR(63) = C(9)
      U_VAR(64) = C(10)
      U_VAR(65) = C(11)
      U_VAR(66) = C(12)
      U_VAR(67) = C(16)
      U_VAR(68) = C(88)
      U_VAR(69) = C(17)
      U_VAR(70) = C(18)
      U_VAR(71) = C(19)
      U_VAR(72) = C(72)
      U_VAR(73) = C(21)
      U_VAR(74) = C(79)
      U_VAR(75) = C(78)
      U_VAR(76) = C(83)
      U_VAR(77) = C(38)
      U_VAR(78) = C(50)
      U_VAR(79) = C(87)
      U_VAR(80) = C(62)
      U_VAR(81) = C(86)
      U_VAR(82) = C(39)
      U_VAR(83) = C(84)
      U_VAR(84) = C(77)
      U_VAR(85) = C(40)
      U_VAR(86) = C(60)
      U_VAR(87) = C(80)
      U_VAR(88) = C(34)
      RETURN
      END

C End of RestConc function                                         
C **************************************************************** 


C **************************************************************** 
C                                                                  
C GetMass - compute total mass of selected atoms                   
C   Arguments :                                                    
C      Mass      - value of mass balance                           
C                                                                  
C **************************************************************** 

      SUBROUTINE GetMass ( Mass )

      INCLUDE 'saprcnov_stem.h'

C Mass - value of mass balance                                     
      REAL*8 Mass(1)

      RETURN
      END

C End of GetMass function                                          
C **************************************************************** 


