!----------------------------------------------
! Module Name : SPECIES
! Generated by: Lex Code
! Usage Instructions: use species
!----------------------------------------------
module SPECIES
	integer::Nospec_transport=66
	integer::Nospec_reactive=88
	integer::Nospec_total=94
	integer, parameter::i_O3=1
	integer, parameter::i_H2O2=2
	integer, parameter::i_NO=3
	integer, parameter::i_NO2=4
	integer, parameter::i_NO3=5
	integer, parameter::i_N2O5=6
	integer, parameter::i_HONO=7
	integer, parameter::i_HNO3=8
	integer, parameter::i_HNO4=9
	integer, parameter::i_SO2=10
	integer, parameter::i_H2SO4=11
	integer, parameter::i_CO=12
	integer, parameter::i_HCHO=13
	integer, parameter::i_CCHO=14
	integer, parameter::i_RCHO=15
	integer, parameter::i_ACET=16
	integer, parameter::i_MEK=17
	integer, parameter::i_HCOOH=18
	integer, parameter::i_MEOH=19
	integer, parameter::i_ETOH=20
	integer, parameter::i_CCO_OH=21
	integer, parameter::i_RCO_OH=22
	integer, parameter::i_GLY=23
	integer, parameter::i_MGLY=24
	integer, parameter::i_BACL=25
	integer, parameter::i_CRES=26
	integer, parameter::i_BALD=27
	integer, parameter::i_ISOPROD=28
	integer, parameter::i_METHACRO=29
	integer, parameter::i_MVK=30
	integer, parameter::i_PROD2=31
	integer, parameter::i_DCB1=32
	integer, parameter::i_DCB2=33
	integer, parameter::i_DCB3=34
	integer, parameter::i_ETHENE=35
	integer, parameter::i_ISOPRENE=36
	integer, parameter::i_C2H6=37
	integer, parameter::i_C3H8=38
	integer, parameter::i_C2H2=39
	integer, parameter::i_C3H6=40
	integer, parameter::i_ALK3=41
	integer, parameter::i_ALK4=42
	integer, parameter::i_ALK5=43
	integer, parameter::i_ARO1=44
	integer, parameter::i_ARO2=45
	integer, parameter::i_OLE1=46
	integer, parameter::i_OLE2=47
	integer, parameter::i_TERP=48
	integer, parameter::i_RNO3=49
	integer, parameter::i_NPHE=50
	integer, parameter::i_PHEN=51
	integer, parameter::i_PAN=52
	integer, parameter::i_PAN2=53
	integer, parameter::i_PBZN=54
	integer, parameter::i_MA_PAN=55
	integer, parameter::i_BC=56
	integer, parameter::i_OC=57
	integer, parameter::i_SSF=58
	integer, parameter::i_SSC=59
	integer, parameter::i_OPM10=60
	integer, parameter::i_OPM25=61
	integer, parameter::i_DUST1=62
	integer, parameter::i_DUST2=63
	integer, parameter::i_DUST3=64
	integer, parameter::i_DMS=65
	integer, parameter::i_CO2=66
	integer, parameter::i_CCO_OOH=67
	integer, parameter::i_RCO_O2=68
	integer, parameter::i_RCO_OOH=69
	integer, parameter::i_XN=70
	integer, parameter::i_XC=71
	integer, parameter::i_O3P=72
	integer, parameter::i_O1D=73
	integer, parameter::i_OH=74
	integer, parameter::i_HO2=75
	integer, parameter::i_C_O2=76
	integer, parameter::i_COOH=77
	integer, parameter::i_ROOH=78
	integer, parameter::i_RO2_R=79
	integer, parameter::i_R2O2=80
	integer, parameter::i_RO2_N=81
	integer, parameter::i_HOCOO=82
	integer, parameter::i_CCO_O2=83
	integer, parameter::i_BZCO_O2=84
	integer, parameter::i_BZNO2_O=85
	integer, parameter::i_BZ_O=86
	integer, parameter::i_MA_RCO3=87
	integer, parameter::i_TBU_O=88
	integer, parameter::i_AIR=89
	integer, parameter::i_N2=90
	integer, parameter::i_O2=91
	integer, parameter::i_H2O=92
	integer, parameter::i_H2=93
	integer, parameter::i_CH4=94
	character(len=16)::SpcName(94)=(/ & 
	'O3       ','H2O2     ','NO       ','NO2      ','NO3      ','N2O5     ' & 
	,'HONO     ','HNO3     ','HNO4     ','SO2      ','H2SO4    ','CO       ' & 
	,'HCHO     ','CCHO     ','RCHO     ','ACET     ','MEK      ','HCOOH    ' & 
	,'MEOH     ','ETOH     ','CCO_OH   ','RCO_OH   ','GLY      ','MGLY     ' & 
	,'BACL     ','CRES     ','BALD     ','ISOPROD  ','METHACRO ','MVK      ' & 
	,'PROD2    ','DCB1     ','DCB2     ','DCB3     ','ETHENE   ','ISOPRENE ' & 
	,'C2H6     ','C3H8     ','C2H2     ','C3H6     ','ALK3     ','ALK4     ' & 
	,'ALK5     ','ARO1     ','ARO2     ','OLE1     ','OLE2     ','TERP     ' & 
	,'RNO3     ','NPHE     ','PHEN     ','PAN      ','PAN2     ','PBZN     ' & 
	,'MA_PAN   ','BC       ','OC       ','SSF      ','SSC      ','OPM10    ' & 
	,'OPM25    ','DUST1    ','DUST2    ','DUST3    ','DMS      ','CO2      ' & 
	,'CCO_OOH  ','RCO_O2   ','RCO_OOH  ','XN       ','XC       ','O3P      ' & 
	,'O1D      ','OH       ','HO2      ','C_O2     ','COOH     ','ROOH     ' & 
	,'RO2_R    ','R2O2     ','RO2_N    ','HOCOO    ','CCO_O2   ','BZCO_O2  ' & 
	,'BZNO2_O  ','BZ_O     ','MA_RCO3  ','TBU_O    ','AIR      ','N2       ' & 
	,'O2       ','H2O      ','H2       ','CH4      '/)
end module SPECIES
